### PR TITLE
I am not cute >:(

### LINKED ISSUE #1: Id like to submit a bug report
In the readme it says:

"y'all cute".

I am not.

Fix this please.

### PR DESCRIPTION
**Pull request by yeSpud**
Fixed #1

### CODE REVIEW

**Comment by yeSpud** [comment]
image

**Review by cyyynthia — CHANGES_REQUESTED** [review]
yall cute no exceptions >:(

**Comment by yeSpud** [comment]
no

**Review by yeSpud — COMMENTED** [review]
Best change

Nothing is wrong

**Comment by yeSpud** [comment]
\>:(

~~tfw cant format~~

**Pull request closed without merging**
